spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 4444
